# Generated by Django 6.0.3 on 2026-03-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdb',
            old_name='Description',
            new_name='Task_Description',
        ),
        migrations.RenameField(
            model_name='taskdb',
            old_name='Title',
            new_name='Task_Title',
        ),
    ]
