# Generated by Django 6.0.3 on 2026-03-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_rename_created_at_projectdb_created_at_and_more'),
        ('tasksapp', '0002_rename_description_taskdb_task_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdb',
            unique_together={('Project', 'Task_Title')},
        ),
    ]
