# Generated by Django 6.0.3 on 2026-03-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0003_alter_taskdb_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdb',
            options={'ordering': ['Due_Date']},
        ),
        migrations.AddField(
            model_name='taskdb',
            name='Priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
