# Generated by Django 6.0.3 on 2026-03-25 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0005_taskcommentdb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachmentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='task_files')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasksapp.taskdb')),
                ('Uploaded_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
