# Generated by Django 6.0.3 on 2026-03-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdb',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='end_date',
            new_name='End_Date',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='description',
            new_name='Project_Description',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='members',
            new_name='Project_Members',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='name',
            new_name='Project_Name',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='owner',
            new_name='Project_Owner',
        ),
        migrations.RenameField(
            model_name='projectdb',
            old_name='start_date',
            new_name='Start_Date',
        ),
    ]
