# Generated by Django 6.0.3 on 2026-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_rename_created_at_projectdb_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdb',
            name='Project_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
